version: '3'

services:

  app-mysql:
    image: mysql:8.0.13
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=contrastdb
      - MYSQL_USER=contrast-user
      - MYSQL_PASSWORD=isaythebestwords
    ports:
      - 3306:3306

  app-main:
    build: .
    image: war-build-img
    restart: on-failure
    depends_on:
      - app-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=app-mysql
      - DATABASE_USER=contrast-user
      - DATABASE_PASSWORD=isaythebestwords
      - DATABASE_NAME=contrastdb
      - DATABASE_PORT=3306